language: go
go_import_path: github.com/clearmatics/ion
go: 1.8.x
script:
  - cd ./ion-cli && make test
notifications:
  slack:
    secure: k6j6BWCTMJ6U7JXhy0yBcJpfkOw4eUNnL9xyufiI6Ue5Cf+NvN9FJxNZvoz4BvVSitq/BSlcWGjQoIW5AoWtf15tl4hvQmFN4YYHT79TKjRGEcSBg1+D55aXmjIM3UwHtCOuSJxAkl7dTgWAJ3FU0/aBqy96OsODjhcP8VeuMay+2Z+kT/QQjtO5rduHfLpeJxVfoEdhXR9QjHozV287rE49E6wWV6KzNCDOYy3CFGkQsgBQzlxkmlvhwbjDeNb72UcruSh50ic78/NLru3AXwRFx2yc1fkr2Nv9q6l5r9I1iWek8EZ46OCe/dQ004s7PI7knVx1vssdA3ksLDyRzhNHvWpn1EI1fi4Aqc+ki9vHbccR5c1pw85zwcQiLEoVFpJ+MpfHi9ExmAJmvvrzz2RBMqsL5JuSfInxiSLyX6vSVpufgZYrDKAemWXhR030dQQZ8BVQOCbt2lzCgHZajmDvrOktq6QdTFzEz/JjyorXn+0Rpho+7FHY5sW9KdgvmexI9SAjjz0BgcQzof9QKpyuRZpbboWRxPsfPUQDlx+Wxm541ndunGNQ2mVXqSgKaTQShiKhhu7dOPevw1a+dreJ6n8afL9pfW4SHcs0O+FlHvAnLAbRDvbnxROF89RRDiTVBdC6h7vcAX6lNDFUxF0F1bYTiWE0s4+umB2zlqc=
